services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama/models
    restart: unless-stopped

  go-client:
    container_name: go-client
    build: 
      context: ./go-client
      target: dev
      args:
        APP_UID: 1000
    environment:
      OPENAI_URL: http://ollama:11434/v1
      OPENAI_API_TOKEN: "something"
    ports:
      - "8000:8000"
      - "3000-3010:3000-3010"
    volumes:
      - ./go-client/:/go/src/go-client/
      - gopkg:/go/pkg/
      - gobin:/go/bin/
    restart: unless-stopped
    tty: true

  weaviate:
    image: semitechnologies/weaviate:1.25.9
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  ollama_models:
  gopkg:
  gobin:
  weaviate_data:
