weaviate:
  scheme: http
  host: weaviate:8080
chats:
  coordinator:
    model: "qwen3:1.7b"
    # model: "mistral-instruct"
    temperature: 0.5
    availableFunctions:
      - get_current_time
      - get_current_weather
      - get_drink_suggestions
      - get_drink_recipe
    prompt:
      role: >
        You are the coordinator responsible for preparing alcoholic drinks for the user.  
        To deliver a drink to the user, you must follow these steps:  
        1. Ask the user what drink they would like.  
        2. If the user doesn’t know, suggest an option and get their confirmation.  
      instructions: >
        - Do not explain your reasoning.
    tmpHttpPort: 3000

  waiter:
    model: "qwen3:1.7b"
    temperature: 0.1
    availableFunctions:
      - get_current_time
      - cocktail_list
    prompt:
      role: >
        You are a waiter who knows the entire menu of drinks available at the bar.
      instructions: >
        - Do not explain your reasoning.
    tmpHttpPort: 3001

  bartender:
    model: "qwen3:1.7b"
    temperature: 0.1
    availableFunctions:
      - get_current_time
      - cocktail_recipe
    promp:
      role: >
        You are a bartender who knows all the drink recipes.
      instructions: >
        - Do not explain your reasoning.
    tmpHttpPort: 3002

  talker:
    model: "qwen3:1.7b"
    temperature: 0.9
    availableFunctions:
      - get_current_time
      - get_current_weather
    prompt:
      role: >
        You are a friendly conversationalist.  
        You chat with the user in a pleasant way and keep the conversation going.  
      instructions: >
        - Do not explain your reasoning.
    tmpHttpPort: 3003

functions:
  get_drink_suggestions:
    url: "http://localhost:3001/api/ask"
    description: "Provide alcoholic drink suggestions based on user guidelines"
    requestTemplate: >
      Context:
      {{ .Context }}

      Provide a concise list of suggested alcoholic drinks based on the following guidelines: {{ .Request }}

  get_drink_recipe:
    url: "http://localhost:3002/api/ask"
    description: "Provide a recipe for an alcoholic drink based on the name provided by the user"
    requestTemplate: >
      Context:
      {{ .Context }}
      
      Provide the recipe for the following alcoholic drink: {{ .Request }}